In [447]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [413]:
df = pd.read_csv("../data/raw data/laptop_dataset_final.csv")

C:\Users\DELL\AppData\Local\Temp\ipykernel_16604\3386281629.py:1: DtypeWarning: Columns (0: Chipset, 1: RAM Speed, 2: Memory Slots, 3: SSD Type, 4: HDMI Ports, 5: Audio Solution, 6: Brightness, 7: Expandable Memory, 8: Thunderbolt Port, 9: VGA Port, 10: HDD Capacity, 11: HDD Speed(RPM), 12: HDD Type, 13: Lockport, 14: Battery Capacity, 15: Aspect Ratio, 16: SSD Interface, 17: Fast Charging Support) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/raw data/laptop_dataset_final.csv")

In [414]:
df.head()

,Brand,Model,Series,Thickness,Dimensions (WxDxH),Weight,Colors,Operating System,Operating System Type,Display Size,...,Lockport,Battery Life,USB Type C,Battery Capacity,Aspect Ratio,Number of Cores,SSD Interface,Fast Charging Support,market_status,Price (Rs)
0,HP,14-dv0055TU (2N1L1PA),Pavilion,17 Millimeter thickness,325 x 216 x 17 mm,1.41 Kg weight (Light-weight),Tranquil Pink,Windows 10 Home Basic,64-bit,14 Inches (35.56 cm),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Available,71990.0
1,Acer,PHN16-71 (NH.QLTSI.002),Predator Helios Neo 16,26.5 Millimeter thickness,361 x 279 x 26.5 mm,2.6 Kg weight,Black,Windows 11 Home Basic,NaN,16 Inches (40.64 cm),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Available,105999.0
2,Dell,15 5570 (A560126WIN9),Inspiron 15,22.7 Millimeter thickness,380 x 258 x 22.7 mm,2.2 Kg weight,Platinum Silver,Windows 10 Home Basic,64-bit,15.6 Inches (39.62 cm),...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Available,54999.0
3,MSI,GV62 7RD-2297XIN,NaN,29 Millimeter thickness,383 x 260 x 29 mm,2.2 Kg weight,Black,DOS,64-bit,15.6 Inches (39.62 cm),...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Available,67990.0
4,Dell,15 3515 (D560702WIN9BE),Inspiron 15,23 Millimeter thickness,358.50 x 17.50 x 23 mm,1.8 Kg weight,"Carbon Black, Platinum Silver",Windows 11 Home Basic,64-bit,15.6 Inches (39.62 cm),...,NaN,7 Hrs,2.0,NaN,NaN,NaN,NaN,NaN,Available,42210.0

In [415]:
df.describe()

,Wi-Fi Version,Bluetooth Version,USB 2.0 slots,Ethernet ports,USB 3.0 slots,USB Type C,Number of Cores,Price (Rs)
count,8124.000000,7380.000000,3225.000000,3444.000000,2223.000000,5191.000000,2925.000000,8177.000000
mean,5.454702,4.859404,1.328062,1.000581,1.692308,1.216336,8.917607,80852.045738
std,0.630616,0.475121,0.494043,0.024095,0.714243,0.450231,4.554171,59390.288254
min,4.000000,2.100000,1.000000,1.000000,1.000000,1.000000,2.000000,8990.000000
25%,5.000000,4.200000,1.000000,1.000000,1.000000,1.000000,6.000000,42490.000000
50%,5.000000,5.000000,1.000000,1.000000,2.000000,1.000000,8.000000,64989.000000
75%,6.000000,5.200000,2.000000,1.000000,2.000000,1.000000,12.000000,96990.000000
max,7.000000,6.000000,3.000000,2.000000,6.000000,4.000000,24.000000,499990.000000

In [416]:
df.isnull().sum()[df.isnull().sum() > 0]

Series                   1093
Thickness                 680
Dimensions (WxDxH)        682
Weight                    307
Colors                    176
                         ...
Aspect Ratio             6869
Number of Cores          5273
SSD Interface            6145
Fast Charging Support    7258
Price (Rs)                 21
Length: 70, dtype: int64

In [417]:
df.isnull().values.any()

np.True_

In [418]:
list(df.columns)

['Brand',
 'Model',
 'Series',
 'Thickness',
 'Dimensions (WxDxH)',
 'Weight',
 'Colors',
 'Operating System',
 'Operating System Type',
 'Display Size',
 'Display Resolution',
 'Pixel Density',
 'Display Type',
 'Display Features',
 'Display Touchscreen',
 'Processor',
 'Clock-speed',
 'Chipset',
 'Cache',
 'Graphic Processor',
 'Capacity',
 'RAM Type',
 'RAM Speed',
 'Memory Slots',
 'Memory Layout',
 'SSD Capacity',
 'SSD Type',
 'Battery Cell',
 'Battery Type',
 'Power Supply',
 'Wireless LAN',
 'Wi-Fi Version',
 'Bluetooth',
 'Bluetooth Version',
 'Other Networking Options',
 'HDMI Ports',
 'USB 2.0 slots',
 'SD Card Reader',
 'Ethernet ports',
 'Headphone Jack',
 'Microphone Jack',
 'Web-cam',
 'Video Recording',
 'Audio Solution',
 'Speakers',
 'Sound Technologies',
 'In-built Microphone',
 'Microphone Type',
 'Pointing device',
 'Keyboard',
 'Fingerprint scanner',
 'Face Recognition',
 'Warranty',
 'Sales Package',
 'Refresh Rate',
 'Brightness',
 'Graphics Memory',
 'Expandable Memory',
 'Thunderbolt Port',
 'VGA Port',
 'Backlit Keyboard',
 'HDD Capacity',
 'HDD Speed(RPM)',
 'HDD Type',
 'USB 3.0 slots',
 'Secondary cam(Rear-facing)',
 'Lockport',
 'Battery Life',
 'USB Type C',
 'Battery Capacity',
 'Aspect Ratio',
 'Number of Cores',
 'SSD Interface',
 'Fast Charging Support',
 'market_status',
 'Price (Rs)']

In [419]:
required_features = [
    'Brand' , 'Model' , 'Series' , 'Weight' , 'Operating System' , 'Operating System Type' , 
     'Display Size' , 'Display Resolution' , 'Pixel Density' , 'Display Touchscreen' , 
     'Processor' , 'Cache' , 'Graphic Processor' , 'Capacity', 'SSD Capacity' , 'SSD Type',
      'Graphics Memory' , 'HDD Capacity' , 'HDD Type' , 'Battery Life' , 'market_status' ,
      'Price (Rs)'
]

In [420]:
# drop all other columns
df = df.drop(columns=[col for col in df.columns if col not in required_features])

In [421]:
df.head()

,Brand,Model,Series,Weight,Operating System,Operating System Type,Display Size,Display Resolution,Pixel Density,Display Touchscreen,...,Graphic Processor,Capacity,SSD Capacity,SSD Type,Graphics Memory,HDD Capacity,HDD Type,Battery Life,market_status,Price (Rs)
0,HP,14-dv0055TU (2N1L1PA),Pavilion,1.41 Kg weight (Light-weight),Windows 10 Home Basic,64-bit,14 Inches (35.56 cm),1920 x 1080 Pixels,157 ppi,No,...,Intel Iris X,16 GB,512 GB,M.2/Optane,NaN,NaN,NaN,NaN,Available,71990.0
1,Acer,PHN16-71 (NH.QLTSI.002),Predator Helios Neo 16,2.6 Kg weight,Windows 11 Home Basic,NaN,16 Inches (40.64 cm),1920 x 1200 Pixels,142 ppi,No,...,NVIDIA GeForce RTX 4050,16 GB,512 GB,NaN,6 GB,NaN,NaN,NaN,Available,105999.0
2,Dell,15 5570 (A560126WIN9),Inspiron 15,2.2 Kg weight,Windows 10 Home Basic,64-bit,15.6 Inches (39.62 cm),1920 x 1080 Pixels,141 ppi,No,...,AMD Radeon 530,8 GB,NaN,NaN,2 GB,2 TB,SATA,NaN,Available,54999.0
3,MSI,GV62 7RD-2297XIN,NaN,2.2 Kg weight,DOS,64-bit,15.6 Inches (39.62 cm),1920 x 1080 Pixels,141 ppi,No,...,NVIDIA GeForce GTX 1050,8 GB,NaN,NaN,4 GB,1 TB,SATA,NaN,Available,67990.0
4,Dell,15 3515 (D560702WIN9BE),Inspiron 15,1.8 Kg weight,Windows 11 Home Basic,64-bit,15.6 Inches (39.62 cm),1920 x 1080 Pixels,141 ppi,No,...,AMD Radeon,4 GB,256 GB,NaN,NaN,NaN,NaN,7 Hrs,Available,42210.0

In [422]:
df.columns

Index(['Brand', 'Model', 'Series', 'Weight', 'Operating System',
       'Operating System Type', 'Display Size', 'Display Resolution',
       'Pixel Density', 'Display Touchscreen', 'Processor', 'Cache',
       'Graphic Processor', 'Capacity', 'SSD Capacity', 'SSD Type',
       'Graphics Memory', 'HDD Capacity', 'HDD Type', 'Battery Life',
       'market_status', 'Price (Rs)'],
      dtype='str')

In [423]:
df.isnull().sum()

Brand                       0
Model                       0
Series                   1093
Weight                    307
Operating System            0
Operating System Type    3520
Display Size                3
Display Resolution         32
Pixel Density              34
Display Touchscreen        82
Processor                   0
Cache                    1571
Graphic Processor          92
Capacity                    0
SSD Capacity             1334
SSD Type                 5744
Graphics Memory          5121
HDD Capacity             6344
HDD Type                 6469
Battery Life             5476
market_status               0
Price (Rs)                 21
dtype: int64

In [424]:
# separating categorical and numerical columns
categorical_cols = df.select_dtypes(include='object').columns
numerical_cols = df.select_dtypes(include=['int64','float64']).columns

C:\Users\DELL\AppData\Local\Temp\ipykernel_16604\1146110786.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include='object').columns

In [425]:
categorical_cols

Index(['Brand', 'Model', 'Series', 'Weight', 'Operating System',
       'Operating System Type', 'Display Size', 'Display Resolution',
       'Pixel Density', 'Display Touchscreen', 'Processor', 'Cache',
       'Graphic Processor', 'Capacity', 'SSD Capacity', 'SSD Type',
       'Graphics Memory', 'HDD Capacity', 'HDD Type', 'Battery Life',
       'market_status'],
      dtype='str')

In [426]:
numerical_cols

Index(['Price (Rs)'], dtype='str')

In [427]:
pipeline = Pipeline([
    ('preprocessing', ColumnTransformer([
        ('cat_impute', SimpleImputer(strategy='most_frequent'), categorical_cols),
        ('num_impute', SimpleImputer(strategy='median'), numerical_cols)
    ]))
])

In [428]:
df = pd.DataFrame(
    pipeline.fit_transform(df),
    columns = list(categorical_cols) + list(numerical_cols)
)

In [429]:
df.isnull().values.any()

np.False_

In [430]:
df.head()

,Brand,Model,Series,Weight,Operating System,Operating System Type,Display Size,Display Resolution,Pixel Density,Display Touchscreen,...,Graphic Processor,Capacity,SSD Capacity,SSD Type,Graphics Memory,HDD Capacity,HDD Type,Battery Life,market_status,Price (Rs)
0,HP,14-dv0055TU (2N1L1PA),Pavilion,1.41 Kg weight (Light-weight),Windows 10 Home Basic,64-bit,14 Inches (35.56 cm),1920 x 1080 Pixels,157 ppi,No,...,Intel Iris X,16 GB,512 GB,M.2/Optane,4 GB,1 TB,SATA,6 Hrs,Available,71990.0
1,Acer,PHN16-71 (NH.QLTSI.002),Predator Helios Neo 16,2.6 Kg weight,Windows 11 Home Basic,64-bit,16 Inches (40.64 cm),1920 x 1200 Pixels,142 ppi,No,...,NVIDIA GeForce RTX 4050,16 GB,512 GB,M.2,6 GB,1 TB,SATA,6 Hrs,Available,105999.0
2,Dell,15 5570 (A560126WIN9),Inspiron 15,2.2 Kg weight,Windows 10 Home Basic,64-bit,15.6 Inches (39.62 cm),1920 x 1080 Pixels,141 ppi,No,...,AMD Radeon 530,8 GB,512 GB,M.2,2 GB,2 TB,SATA,6 Hrs,Available,54999.0
3,MSI,GV62 7RD-2297XIN,Ideapad,2.2 Kg weight,DOS,64-bit,15.6 Inches (39.62 cm),1920 x 1080 Pixels,141 ppi,No,...,NVIDIA GeForce GTX 1050,8 GB,512 GB,M.2,4 GB,1 TB,SATA,6 Hrs,Available,67990.0
4,Dell,15 3515 (D560702WIN9BE),Inspiron 15,1.8 Kg weight,Windows 11 Home Basic,64-bit,15.6 Inches (39.62 cm),1920 x 1080 Pixels,141 ppi,No,...,AMD Radeon,4 GB,256 GB,M.2,4 GB,1 TB,SATA,7 Hrs,Available,42210.0

In [431]:
df_encoded=df.copy()

In [432]:
label_encoders = {}

In [433]:
df_encoded.dtypes

Brand                       str
Model                       str
Series                      str
Weight                      str
Operating System            str
Operating System Type       str
Display Size                str
Display Resolution          str
Pixel Density               str
Display Touchscreen         str
Processor                   str
Cache                       str
Graphic Processor           str
Capacity                    str
SSD Capacity                str
SSD Type                    str
Graphics Memory             str
HDD Capacity                str
HDD Type                    str
Battery Life                str
market_status               str
Price (Rs)               object
dtype: object

In [434]:
#converting categorical columns to numerical columns

#weight
df['Weight'] = pd.to_numeric(
    df['Weight'].astype(str).str.extract(r'([\d.]+)')[0],
    errors='coerce'
)

#display size
df['Display Size'] = pd.to_numeric(
    df['Display Size'].astype(str).str.extract(r'([\d.]+)')[0],
    errors='coerce'
)

#display resolution
res = df['Display Resolution'].astype(str).str.extract(r'(\d+)\D+(\d+)')

df['Resolution_X'] = pd.to_numeric(res[0], errors='coerce')
df['Resolution_Y'] = pd.to_numeric(res[1], errors='coerce')

df = df.drop(columns=['Display Resolution'])

#pixel density
df['Pixel Density'] = pd.to_numeric(
    df['Pixel Density'].astype(str).str.extract(r'(\d+)')[0],
    errors='coerce'
)

#capacity
df['Capacity'] = pd.to_numeric(
    df['Capacity'].astype(str).str.extract(r'(\d+)')[0],
    errors='coerce'
)

#graphics memory
df['Graphics Memory'] = pd.to_numeric(
    df['Graphics Memory'].astype(str).str.extract(r'(\d+)')[0],
    errors='coerce'
)

#battery life
df['Battery Life'] = pd.to_numeric(
    df['Battery Life'].astype(str).str.extract(r'([\d.]+)')[0],
    errors='coerce'
)

#cache
df['Cache'] = pd.to_numeric(
    df['Cache'].astype(str).str.extract(r'(\d+)')[0],
    errors='coerce'
)

# #SSD Capacity
# df['SSD Capacity'] = pd.to_numeric(
#     df['SSD Capacity'].astype(str).str.extract(r'(\d+)')[0],
#     errors='coerce'
# )

In [435]:
#function to convert hdd
def convert_hdd(x):
    x = str(x).upper()
    if 'TB' in x:
        return float(x.replace('TB','').strip()) * 1024
    elif 'GB' in x:
        return float(x.replace('GB','').strip())
    return None

# HDD Capacity
df['HDD Capacity'] = df['HDD Capacity'].apply(convert_hdd)

In [436]:
#function to convert ssd
def convert_ssd(x):
    x = str(x).upper()
    
    if 'SSD' in x:
        if 'TB' in x:
            return int(x.split('TB')[0].split()[-1]) * 1024
        else:
            return int(x.split('GB')[0].split()[-1])
    else:
        return 0

df['SSD Capacity'] = df['SSD Capacity'].apply(convert_ssd)

In [437]:
#Binary Columns

# Display Touchscreen
df['Display Touchscreen'] = df['Display Touchscreen'].astype(str).str.strip().str.upper()
df['Display Touchscreen'] = df['Display Touchscreen'].map({'YES':1, 'NO':0})

# Operating System Type
df['Operating System Type'] = df['Operating System Type'].astype(str).str.strip()
df['Operating System Type'] = df['Operating System Type'].map({'32-bit':0, '64-bit':1})

# market_status
df['market_status'] = df['market_status'].astype(str).str.strip().str.upper()
df['market_status'] = df['market_status'].map({'AVAILABLE':1, 'OUT OF STOCK':0})

In [438]:
#Other categorical columns(Label Encoding)

categorical_cols = ['Brand','Model','Series','Operating System','Graphic Processor',
                    'SSD Type','HDD Type']

for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

In [455]:
#processor(extracting cpu brand and cpu model)
#extract cpu brand
def cpu_brand(x):
    x = str(x).upper()

    if 'INTEL' in x:
        return 'Intel'
    elif 'AMD' in x:
        return 'AMD'
    elif 'M1' in x or 'M2' in x:
        return 'Apple'
    else:
        return 'Other'

df['cpu_brand'] = df['Processor'].apply(cpu_brand)

#extract cpu model
def cpu_model(x):
    x = str(x).upper()

    if 'I3' in x or 'RYZEN 3' in x:
        return 3
    elif 'I5' in x or 'RYZEN 5' in x:
        return 5
    elif 'I7' in x or 'RYZEN 7' in x:
        return 7
    elif 'I9' in x:
        return 9
    elif 'PENTIUM' in x:
        return 2
    elif 'CELERON' in x:
        return 1
    else:
        return 4

df['cpu_model'] = df['Processor'].apply(cpu_model)

df.drop('Processor', axis=1, inplace=True)

#convert cpu_brand to numerical
df['cpu_brand'] = df['cpu_brand'].map({
    'Intel': 0,
    'AMD': 1,
    'Apple': 2,
    'Other': 3
})

In [456]:
col1 = df.pop('Resolution_X')
col2 = df.pop('Resolution_Y')

df.insert(7,'Resolution_X',col1)
df.insert(8,'Resolution_Y',col2)

In [461]:
col1 = df.pop('cpu_brand')
col2 = df.pop('cpu_model')

df.insert(10,'cpu_brand',col1)
df.insert(11,'cpu_model',col2)

In [462]:
df.head()

,Brand,Model,Series,Weight,Operating System,Operating System Type,Display Size,Resolution_X,Resolution_Y,Pixel Density,...,Graphic Processor,Capacity,SSD Capacity,SSD Type,Graphics Memory,HDD Capacity,HDD Type,Battery Life,market_status,Price (Rs)
0,9,945,243,1.41,12,1,14.0,1920,1080,157,...,154,16,0,1,4,1024.0,0,6.0,1,71990.0
1,0,6510,258,2.60,16,1,16.0,1920,1200,142,...,266,16,0,0,6,1024.0,0,6.0,1,105999.0
2,6,1428,168,2.20,12,1,15.6,1920,1080,141,...,8,8,0,0,2,2048.0,0,6.0,1,54999.0
3,16,5470,156,2.20,0,1,15.6,1920,1080,141,...,201,8,0,0,4,1024.0,0,6.0,1,67990.0
4,6,1340,168,1.80,16,1,15.6,1920,1080,141,...,4,4,0,0,4,1024.0,0,7.0,1,42210.0

In [463]:
df.rename(columns={
    'Weight' : 'Weight(Kg)',
    'Display Size' : 'Display Size(inches)',
    'Resolution_X' : 'Resolution_X(pixel)',
    'Resolution_Y' : 'Resolution_Y(pixel)',
    'Pixel Density' : 'Pixel Density(ppi)',
    'Capacity' : 'Capacity(GB)',
    'SSD Capacity' : 'SSD Capacity(GB)',
    'Graphics Memory' : 'Graphics Memory(GB)',
    'HDD Capacity' : 'HDD Capacity(GB)',
    'Battery Life' : 'Battery Life(Hrs)'
})

,Brand,Model,Series,Weight(Kg),Operating System,Operating System Type,Display Size(inches),Resolution_X(pixel),Resolution_Y(pixel),Pixel Density(ppi),...,Graphic Processor,Capacity(GB),SSD Capacity(GB),SSD Type,Graphics Memory(GB),HDD Capacity(GB),HDD Type,Battery Life(Hrs),market_status,Price (Rs)
0,9,945,243,1.41,12,1,14.0,1920,1080,157,...,154,16,0,1,4,1024.0,0,6.0,1,71990.0
1,0,6510,258,2.60,16,1,16.0,1920,1200,142,...,266,16,0,0,6,1024.0,0,6.0,1,105999.0
2,6,1428,168,2.20,12,1,15.6,1920,1080,141,...,8,8,0,0,2,2048.0,0,6.0,1,54999.0
3,16,5470,156,2.20,0,1,15.6,1920,1080,141,...,201,8,0,0,4,1024.0,0,6.0,1,67990.0
4,6,1340,168,1.80,16,1,15.6,1920,1080,141,...,4,4,0,0,4,1024.0,0,7.0,1,42210.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8193,0,3335,56,2.10,12,1,15.6,3840,2160,282,...,251,32,0,0,8,1024.0,0,6.0,0,260999.0
8194,0,3334,56,2.10,12,1,15.6,3840,2160,282,...,251,32,0,0,8,1024.0,0,6.0,0,255999.0
8195,15,7596,402,1.22,14,1,13.3,1920,1080,166,...,160,8,0,0,4,1024.0,0,6.0,0,115900.0
8196,15,4338,402,1.77,0,1,14.0,1920,1080,157,...,160,8,0,0,4,1024.0,0,6.0,0,59073.0
8197,15,7935,189,2.30,12,1,15.6,1920,1080,141,...,293,16,0,0,4,1024.0,0,5.0,0,105999.0

In [464]:
df.isnull().sum()

Brand                    0
Model                    0
Series                   0
Weight                   0
Operating System         0
Operating System Type    0
Display Size             0
Resolution_X             0
Resolution_Y             0
Pixel Density            0
cpu_brand                0
cpu_model                0
Display Touchscreen      0
Cache                    0
Graphic Processor        0
Capacity                 0
SSD Capacity             0
SSD Type                 0
Graphics Memory          0
HDD Capacity             0
HDD Type                 0
Battery Life             0
market_status            0
Price (Rs)               0
dtype: int64

In [465]:
df.isnull().values.any()

np.False_